// Portrait crop for catalog cards and the wine page, landscape for feed posts.
const img = (slug: string) => `/images/wines/${slug}.webp`
const wide = (slug: string) => `/images/wines/${slug}-wide.webp`
// Seeded users have photos; guest.svg stays as the placeholder for sign-ups.
const ava = (slug: string) => `/images/avatars/${slug}.webp`

const daysAgo = (d: number, h = 0) =>
  new Date(Date.now() - d * 86_400_000 - h * 3_600_000).toISOString()

export const users = [
  {
    id: 'u1',
    name: 'Анна Ковалёва',
    email: 'anna@vinora.ru',
    avatar: ava('anna'),
    bio: 'Сомелье, влюблена в крымские автохтоны и бургундский пино нуар.',
    location: 'Ялта',
    stats: { posts: 42, reviews: 128, followers: 1840, following: 212 },
    isFollowing: true,
  },
  {
    id: 'u2',
    name: 'Дмитрий Соколов',
    email: 'dmitry@vinora.ru',
    avatar: ava('dmitry'),
    bio: 'Собираю погреб пять лет. Веду заметки о каждой бутылке.',
    location: 'Москва',
    stats: { posts: 31, reviews: 96, followers: 720, following: 140 },
    isFollowing: false,
  },
  {
    id: 'u3',
    name: 'Елена Морозова',
    email: 'elena@vinora.ru',
    avatar: ava('elena'),
    bio: 'Игристое — это настроение, а не повод.',
    location: 'Санкт-Петербург',
    stats: { posts: 58, reviews: 210, followers: 3120, following: 308 },
    isFollowing: true,
  },
  {
    id: 'u4',
    name: 'Игорь Волков',
    email: 'igor@vinora.ru',
    avatar: ava('igor'),
    bio: 'Ресторатор. Ищу вино, которое переживёт мой стейк.',
    location: 'Краснодар',
    stats: { posts: 19, reviews: 64, followers: 480, following: 96 },
    isFollowing: false,
  },
  {
    id: 'u5',
    name: 'Мария Литвинова',
    email: 'maria@vinora.ru',
    avatar: ava('maria'),
    bio: 'Белое, холодное, с видом на море.',
    location: 'Севастополь',
    stats: { posts: 27, reviews: 88, followers: 910, following: 175 },
    isFollowing: false,
  },
  {
    id: 'u6',
    name: 'Павел Гринёв',
    email: 'pavel@vinora.ru',
    avatar: ava('pavel'),
    bio: 'Винный блогер. Дегустирую вслепую и не стесняюсь ошибаться.',
    location: 'Казань',
    stats: { posts: 64, reviews: 302, followers: 5400, following: 411 },
    isFollowing: true,
  },
  {
    id: 'u7',
    name: 'София Райт',
    email: 'sofia@vinora.ru',
    avatar: ava('sofia'),
    bio: 'Импортирую малые хозяйства из Пьемонта и Луары.',
    location: 'Нижний Новгород',
    stats: { posts: 23, reviews: 71, followers: 660, following: 88 },
    isFollowing: false,
  },
]

export const wines = [
  {
    id: 'w1',
    name: 'Каберне Совиньон Резерв',
    producer: 'Алма Валлей',
    country: 'Россия',
    region: 'Крым',
    color: 'red',
    category: 'still',
    sweetness: 'dry',
    grapes: ['Каберне Совиньон'],
    year: 2019,
    abv: 14,
    price: 2490,
    rating: 4.6,
    ratingsCount: 412,
    image: img('cabernet'),
    description:
      'Плотное крымское каберне с ароматом чёрной смородины, кедра и лёгкой дымности. Год в французском дубе дал бархатистые танины и долгое послевкусие.',
    pairing: ['Стейк рибай', 'Баранина на углях', 'Выдержанный чеддер'],
    awards: ['Золото Vinorus 2023'],
    taste: { body: 5, tannins: 4, acidity: 3, sweetness: 1, fruitiness: 4 },
    similarIds: ['w2', 'w4', 'w3'],
  },
  {
    id: 'w2',
    name: 'Саперави Старый Погреб',
    producer: 'Фанагория',
    country: 'Россия',
    region: 'Краснодарский край',
    color: 'red',
    category: 'still',
    sweetness: 'dry',
    grapes: ['Саперави'],
    year: 2020,
    abv: 13.5,
    price: 1790,
    rating: 4.4,
    ratingsCount: 318,
    image: img('saperavi'),
    description:
      'Тёмное, почти чернильное вино. Спелая вишня, чернослив и нотка табака. Танины крепкие, но округлые — идеально к мясу.',
    pairing: ['Шашлык', 'Тушёная телятина', 'Твёрдые сыры'],
    awards: [],
    taste: { body: 5, tannins: 5, acidity: 3, sweetness: 1, fruitiness: 3 },
    similarIds: ['w1', 'w4', 'w3'],
  },
  {
    id: 'w3',
    name: 'Пино Нуар Кот-де-Нюи',
    producer: 'Domaine Lascombe',
    country: 'Франция',
    region: 'Франция',
    color: 'red',
    category: 'still',
    sweetness: 'dry',
    grapes: ['Пино Нуар'],
    year: 2021,
    abv: 13,
    price: 5900,
    rating: 4.8,
    ratingsCount: 264,
    image: img('pinot-noir'),
    description:
      'Классическая Бургундия: малина, влажная земля, подлесок. Шелковистая текстура и кислотность, которая держит вино живым до последнего глотка.',
    pairing: ['Утиная грудка', 'Грибное ризотто', 'Мягкие сыры'],
    awards: ['Decanter Silver 2023'],
    taste: { body: 3, tannins: 3, acidity: 4, sweetness: 1, fruitiness: 4 },
    similarIds: ['w1', 'w4', 'w12'],
  },
  {
    id: 'w4',
    name: 'Мерло Ризерва',
    producer: 'Cantina Bellavista',
    country: 'Италия',
    region: 'Италия',
    color: 'red',
    category: 'still',
    sweetness: 'semi-dry',
    grapes: ['Мерло', 'Санджовезе'],
    year: 2018,
    abv: 13.5,
    price: 3450,
    rating: 4.3,
    ratingsCount: 196,
    image: img('merlot'),
    description:
      'Мягкое тосканское мерло с нотами сливы, ванили и сушёных трав. Пять лет в бутылке сгладили все углы.',
    pairing: ['Паста болоньезе', 'Пицца', 'Прошутто'],
    awards: ['Gambero Rosso · 2 бокала'],
    taste: { body: 4, tannins: 3, acidity: 3, sweetness: 2, fruitiness: 4 },
    similarIds: ['w2', 'w1', 'w3'],
  },
  {
    id: 'w5',
    name: 'Шардоне Бочковое',
    producer: 'Золотая Балка',
    country: 'Россия',
    region: 'Крым',
    color: 'white',
    category: 'still',
    sweetness: 'dry',
    grapes: ['Шардоне'],
    year: 2022,
    abv: 13,
    price: 1590,
    rating: 4.2,
    ratingsCount: 287,
    image: img('chardonnay'),
    description:
      'Сливочное шардоне с ароматом печёного яблока, ванили и лёгкого миндаля. Ферментация в дубе, но без перебора.',
    pairing: ['Запечённая курица', 'Паста с грибами', 'Бри'],
    awards: ['Серебро Vinorus 2023'],
    taste: { body: 4, tannins: 1, acidity: 3, sweetness: 2, fruitiness: 3 },
    similarIds: ['w8', 'w6', 'w7'],
  },
  {
    id: 'w6',
    name: 'Рислинг Кабинет',
    producer: 'Weingut Hoffmann',
    country: 'Германия',
    region: 'Франция',
    color: 'white',
    category: 'still',
    sweetness: 'semi-sweet',
    grapes: ['Рислинг'],
    year: 2021,
    abv: 10.5,
    price: 2890,
    rating: 4.7,
    ratingsCount: 158,
    image: img('riesling'),
    description:
      'Лайм, зелёное яблоко и характерная минеральность. Сахар идеально уравновешен звенящей кислотностью.',
    pairing: ['Тайская кухня', 'Суши', 'Козий сыр'],
    awards: ['Mundus Vini Gold 2022'],
    taste: { body: 2, tannins: 1, acidity: 5, sweetness: 3, fruitiness: 5 },
    similarIds: ['w7', 'w5', 'w8'],
  },
  {
    id: 'w7',
    name: 'Совиньон Блан Луара',
    producer: 'Maison Verte',
    country: 'Франция',
    region: 'Франция',
    color: 'white',
    category: 'still',
    sweetness: 'dry',
    grapes: ['Совиньон Блан'],
    year: 2022,
    abv: 12.5,
    price: 2350,
    rating: 4.5,
    ratingsCount: 203,
    image: img('sauvignon'),
    description:
      'Крыжовник, свежескошенная трава и кремень. Хрустящее, бодрое вино для жаркого дня.',
    pairing: ['Устрицы', 'Салат с козьим сыром', 'Севиче'],
    awards: [],
    taste: { body: 2, tannins: 1, acidity: 5, sweetness: 1, fruitiness: 4 },
    similarIds: ['w6', 'w8', 'w5'],
  },
  {
    id: 'w8',
    name: 'Ркацители Оранж',
    producer: 'Усадьба Дивноморское',
    country: 'Россия',
    region: 'Краснодарский край',
    color: 'orange',
    category: 'still',
    sweetness: 'dry',
    grapes: ['Ркацители'],
    year: 2020,
    abv: 12.5,
    price: 2190,
    rating: 4.1,
    ratingsCount: 122,
    image: img('rkatsiteli'),
    description:
      'Оранжевое вино на мезге: абрикосовая косточка, чайный лист, лёгкая танинная хватка. Для тех, кто ищет необычное.',
    pairing: ['Хачапури', 'Пряная баранина', 'Хамон'],
    awards: ['Открытие года · Wine Guide 2023'],
    taste: { body: 3, tannins: 3, acidity: 4, sweetness: 1, fruitiness: 3 },
    similarIds: ['w5', 'w7', 'w6'],
  },
  {
    id: 'w9',
    name: 'Розе де Прованс',
    producer: 'Château du Mistral',
    country: 'Франция',
    region: 'Франция',
    color: 'rose',
    category: 'still',
    sweetness: 'dry',
    grapes: ['Гренаш', 'Сенсо'],
    year: 2023,
    abv: 12.5,
    price: 3100,
    rating: 4.6,
    ratingsCount: 241,
    image: img('rose-provence'),
    description:
      'Бледно-лососевый цвет, аромат грейпфрута и персика. Сухое, лёгкое, безупречно освежающее.',
    pairing: ['Морепродукты', 'Летние салаты', 'Тартар из лосося'],
    awards: ['Concours Mondial Silver 2023'],
    taste: { body: 2, tannins: 1, acidity: 4, sweetness: 1, fruitiness: 4 },
    similarIds: ['w10', 'w7', 'w11'],
  },
  {
    id: 'w10',
    name: 'Розовое Массандра',
    producer: 'Массандра',
    country: 'Россия',
    region: 'Крым',
    color: 'rose',
    category: 'fortified',
    sweetness: 'semi-sweet',
    grapes: ['Бастардо', 'Каберне Совиньон'],
    year: 2022,
    abv: 16,
    price: 1290,
    rating: 4.0,
    ratingsCount: 176,
    image: img('rose-crimea'),
    description:
      'Клубника со сливками в бокале. Креплёное полусладкое, простое и очень дружелюбное — отличный старт для новичка.',
    pairing: ['Фруктовые десерты', 'Панна-котта', 'Сырная тарелка'],
    awards: [],
    taste: { body: 2, tannins: 1, acidity: 3, sweetness: 4, fruitiness: 5 },
    similarIds: ['w9', 'w11', 'w6'],
  },
  {
    id: 'w11',
    name: 'Просекко Супериоре',
    producer: 'Valdo Colli',
    country: 'Италия',
    region: 'Италия',
    color: 'white',
    category: 'sparkling',
    sweetness: 'semi-dry',
    grapes: ['Глера'],
    year: 2022,
    abv: 11.5,
    price: 1990,
    rating: 4.3,
    ratingsCount: 356,
    image: img('prosecco'),
    description:
      'Мелкий стойкий перляж, груша, белые цветы и немного мёда. Лёгкое игристое на каждый день.',
    pairing: ['Аперитив', 'Брускетта', 'Фруктовая тарелка'],
    awards: [],
    taste: { body: 2, tannins: 1, acidity: 4, sweetness: 2, fruitiness: 4 },
    similarIds: ['w12', 'w9', 'w10'],
  },
  {
    id: 'w12',
    name: 'Брют Миллезим',
    producer: 'Абрау-Дюрсо',
    country: 'Россия',
    region: 'Краснодарский край',
    color: 'white',
    category: 'sparkling',
    sweetness: 'dry',
    grapes: ['Шардоне', 'Пино Нуар'],
    year: 2017,
    abv: 12.5,
    price: 4200,
    rating: 4.7,
    ratingsCount: 289,
    image: img('champagne'),
    description:
      'Классический метод, 48 месяцев на осадке. Бриошь, лесной орех, цитрусовая цедра и кремовая пена.',
    pairing: ['Икра', 'Гребешки', 'Выдержанный комте'],
    awards: ['Гран-при Абрау 2022', 'Золото Vinorus 2023'],
    taste: { body: 3, tannins: 1, acidity: 5, sweetness: 1, fruitiness: 3 },
    similarIds: ['w11', 'w5', 'w3'],
  },
]

const brief = (id: string) => {
  const u = users.find((x) => x.id === id) ?? users[0]
  return { id: u.id, name: u.name, avatar: u.avatar }
}

const comment = (
  id: string,
  postId: string,
  authorId: string,
  text: string,
  days: number,
) => ({ id, postId, author: brief(authorId), text, createdAt: daysAgo(days) })

export const posts = [
  {
    id: 'p1',
    author: brief('u1'),
    wineId: 'w1',
    wineName: 'Каберне Совиньон Резерв',
    image: wide('cabernet'),
    text: 'Открыла на террасе в Ялте: первые двадцать минут вино молчало, потом раскрылось смородиной и кедром. Крым умеет.',
    rating: 4.7,
    tags: ['Крым', 'Каберне', 'Выдержка'],
    likes: 214,
    likedByMe: false,
    savedByMe: true,
    commentsCount: 3,
    comments: [
      comment('c1', 'p1', 'u2', 'Брал в прошлом месяце — согласен, нужно декантировать.', 2),
      comment('c2', 'p1', 'u6', 'А с каким годом сравнивали?', 1),
      comment('c3', 'p1', 'u5', 'Добавила в избранное, спасибо за наводку!', 1),
    ],
    createdAt: daysAgo(0, 3),
  },
  {
    id: 'p2',
    author: brief('u6'),
    wineId: 'w3',
    wineName: 'Пино Нуар Кот-де-Нюи',
    image: wide('pinot-noir'),
    text: 'Слепая дегустация: угадал регион с первого глотка. Эта земляная нота ни с чем не спутать.',
    rating: 4.9,
    tags: ['Бургундия', 'Пино Нуар', 'Слепая дегустация'],
    likes: 389,
    likedByMe: true,
    savedByMe: false,
    commentsCount: 2,
    comments: [
      comment('c4', 'p2', 'u7', 'Классика! У нас похожий лот приехал на прошлой неделе.', 2),
      comment('c5', 'p2', 'u3', 'Цена кусается, но оно того стоит.', 1),
    ],
    createdAt: daysAgo(0, 8),
  },
  {
    id: 'p3',
    author: brief('u3'),
    wineId: 'w12',
    wineName: 'Брют Миллезим',
    image: wide('champagne'),
    text: 'Четыре года на осадке слышно в каждом пузырьке. Бриошь, орех и совершенно неприличная лёгкость.',
    rating: 4.8,
    tags: ['Игристое', 'Брют', 'Абрау'],
    likes: 452,
    likedByMe: false,
    savedByMe: false,
    commentsCount: 2,
    comments: [
      comment('c6', 'p3', 'u1', 'Лучшее российское игристое в этой цене, без вариантов.', 3),
      comment('c7', 'p3', 'u4', 'Поставил в карту ресторана, гости в восторге.', 2),
    ],
    createdAt: daysAgo(1, 2),
  },
  {
    id: 'p4',
    author: brief('u5'),
    wineId: 'w7',
    wineName: 'Совиньон Блан Луара',
    image: wide('sauvignon'),
    text: 'Тридцать градусов, устрицы и этот совиньон. Больше ничего для счастья не нужно.',
    rating: 4.5,
    tags: ['Луара', 'Белое', 'Лето'],
    likes: 176,
    likedByMe: false,
    savedByMe: false,
    commentsCount: 1,
    comments: [comment('c8', 'p4', 'u2', 'Отличный кадр! Где брали?', 2)],
    createdAt: daysAgo(1, 9),
  },
  {
    id: 'p5',
    author: brief('u2'),
    wineId: 'w2',
    wineName: 'Саперави Старый Погреб',
    image: wide('saperavi'),
    text: 'Достал из погреба бутылку 2020-го. Танины наконец-то успокоились — ещё пара лет и будет идеально.',
    rating: 4.4,
    tags: ['Саперави', 'Погреб', 'Кубань'],
    likes: 132,
    likedByMe: false,
    savedByMe: false,
    commentsCount: 2,
    comments: [
      comment('c9', 'p5', 'u4', 'К шашлыку вообще бомба.', 3),
      comment('c10', 'p5', 'u6', 'Сколько держали?', 2),
    ],
    createdAt: daysAgo(2, 1),
  },
  {
    id: 'p6',
    author: brief('u7'),
    wineId: 'w9',
    wineName: 'Розе де Прованс',
    image: wide('rose-provence'),
    text: 'Новая поставка приехала. Цвет — лепесток розы, аромат — грейпфрут. Прованс в чистом виде.',
    rating: 4.6,
    tags: ['Прованс', 'Розе', 'Импорт'],
    likes: 298,
    likedByMe: true,
    savedByMe: true,
    commentsCount: 1,
    comments: [comment('c11', 'p6', 'u5', 'Хочу! Есть в рознице?', 2)],
    createdAt: daysAgo(2, 7),
  },
  {
    id: 'p7',
    author: brief('u4'),
    wineId: 'w4',
    wineName: 'Мерло Ризерва',
    image: wide('merlot'),
    text: 'Поставил к пасте с рагу — гости просили добавки. Мягкое, округлое, без единого острого угла.',
    rating: 4.2,
    tags: ['Тоскана', 'Мерло', 'Гастро'],
    likes: 94,
    likedByMe: false,
    savedByMe: false,
    commentsCount: 1,
    comments: [comment('c12', 'p7', 'u7', 'Прошутто к нему — must have.', 3)],
    createdAt: daysAgo(3, 4),
  },
  {
    id: 'p8',
    author: brief('u1'),
    wineId: 'w6',
    wineName: 'Рислинг Кабинет',
    image: wide('riesling'),
    text: 'Тот случай, когда полусладкое не про сахар, а про баланс. Кислотность вытягивает всё вино вверх.',
    rating: 4.8,
    tags: ['Рислинг', 'Германия', 'Баланс'],
    likes: 265,
    likedByMe: false,
    savedByMe: false,
    commentsCount: 2,
    comments: [
      comment('c13', 'p8', 'u3', 'К тайской еде — лучшее сочетание на свете.', 4),
      comment('c14', 'p8', 'u6', 'Полностью поддерживаю, рислинг недооценён.', 3),
    ],
    createdAt: daysAgo(3, 10),
  },
  {
    id: 'p9',
    author: brief('u3'),
    wineId: 'w11',
    wineName: 'Просекко Супериоре',
    image: wide('prosecco'),
    text: 'Пятничный аперитив. Груша, белые цветы и ощущение, что выходные уже начались.',
    rating: 4.3,
    tags: ['Просекко', 'Аперитив', 'Пятница'],
    likes: 187,
    likedByMe: false,
    savedByMe: false,
    commentsCount: 1,
    comments: [comment('c15', 'p9', 'u5', 'Мой дежурный вариант на все случаи.', 4)],
    createdAt: daysAgo(4, 2),
  },
  {
    id: 'p10',
    author: brief('u6'),
    wineId: 'w8',
    wineName: 'Ркацители Оранж',
    image: wide('rkatsiteli'),
    text: 'Оранж на мезге из Краснодара. Танины в белом вине — звучит странно, работает отлично.',
    rating: 4.1,
    tags: ['Оранж', 'Ркацители', 'Эксперимент'],
    likes: 143,
    likedByMe: false,
    savedByMe: false,
    commentsCount: 2,
    comments: [
      comment('c16', 'p10', 'u2', 'Пробовал — непривычно, но затягивает.', 5),
      comment('c17', 'p10', 'u1', 'К хачапури просто идеально.', 4),
    ],
    createdAt: daysAgo(5, 1),
  },
  {
    id: 'p11',
    author: brief('u5'),
    wineId: 'w5',
    wineName: 'Шардоне Бочковое',
    image: wide('chardonnay'),
    text: 'Севастопольский закат и бокал шардоне. Дуб есть, но он не кричит — ровно столько, сколько нужно.',
    rating: 4.2,
    tags: ['Шардоне', 'Крым', 'Закат'],
    likes: 221,
    likedByMe: false,
    savedByMe: false,
    commentsCount: 1,
    comments: [comment('c18', 'p11', 'u4', 'За эти деньги — отличное соотношение.', 5)],
    createdAt: daysAgo(6, 3),
  },
  {
    id: 'p12',
    author: brief('u2'),
    wineId: 'w10',
    wineName: 'Розовое Массандра',
    image: wide('rose-crimea'),
    text: 'Взял на пикник как простое вино — а получил клубнику со сливками. Иногда простое и есть лучшее.',
    rating: 4.0,
    tags: ['Массандра', 'Розе', 'Пикник'],
    likes: 88,
    likedByMe: false,
    savedByMe: false,
    commentsCount: 1,
    comments: [comment('c19', 'p12', 'u3', 'Отличный вариант для начинающих.', 6)],
    createdAt: daysAgo(7, 5),
  },
]

const review = (
  id: string,
  wineId: string,
  authorId: string,
  rating: number,
  text: string,
  days: number,
) => ({ id, wineId, author: brief(authorId), rating, text, createdAt: daysAgo(days) })

export const reviews = [
  review('r1', 'w1', 'u1', 5, 'Эталон крымского каберне. Дайте ему подышать полчаса.', 1),
  review('r2', 'w1', 'u4', 4, 'Отлично к мясу, но в молодости слишком плотное.', 4),
  review('r3', 'w1', 'u6', 5, 'Лучшее соотношение цены и характера в своей категории.', 8),
  review('r4', 'w2', 'u2', 4, 'Мощное, тёмное, очень кубанское. Танины пока острые.', 2),
  review('r5', 'w2', 'u4', 5, 'Мой постоянный выбор к шашлыку. Не подводит.', 6),
  review('r6', 'w3', 'u6', 5, 'Настоящая Бургундия. Шелк и подлесок.', 1),
  review('r7', 'w3', 'u7', 5, 'Дорого, но это тот случай, когда цена оправдана.', 5),
  review('r8', 'w3', 'u3', 4, 'Изящно, хотя ждала чуть больше глубины.', 9),
  review('r9', 'w4', 'u4', 4, 'Мягкое и предсказуемое — в хорошем смысле.', 3),
  review('r10', 'w4', 'u7', 4, 'Прекрасно к пасте, лишних амбиций нет.', 7),
  review('r11', 'w5', 'u5', 4, 'Сливочное, но не масляное. Баланс найден.', 2),
  review('r12', 'w5', 'u1', 4, 'Хорошая работа с дубом за небольшие деньги.', 10),
  review('r13', 'w6', 'u1', 5, 'Кислотность как лезвие. Обожаю.', 3),
  review('r14', 'w6', 'u3', 5, 'Полусладкое, которое не стыдно поставить на стол.', 6),
  review('r15', 'w7', 'u5', 5, 'Крыжовник и кремень — учебник по совиньону.', 1),
  review('r16', 'w7', 'u2', 4, 'Освежает мгновенно, но забывается быстро.', 8),
  review('r17', 'w8', 'u6', 4, 'Необычный оранж, к пряной кухне — отлично.', 4),
  review('r18', 'w8', 'u2', 4, 'Танины в белом вине оказались приятным сюрпризом.', 11),
  review('r19', 'w9', 'u7', 5, 'Прованс как он есть. Идеальный цвет.', 2),
  review('r20', 'w9', 'u5', 4, 'Лёгкое и элегантное, но хотелось бы подешевле.', 9),
  review('r21', 'w10', 'u3', 4, 'Простое, сладковатое, очень летнее.', 5),
  review('r22', 'w11', 'u3', 4, 'Стабильное игристое на каждый день.', 3),
  review('r23', 'w12', 'u1', 5, 'Метод классический слышен сразу. Бриошь и орех.', 2),
  review('r24', 'w12', 'u6', 5, 'Держит уровень многих шампанских вдвое дороже.', 7),
]
